name: SpawnPort
main: SpawnPort\SpawnPort
version: 0.1
api: [1.13.0]

load: POSTWORLD
author: ecoron
description: teleport player to worldspawn
website: https://github.com/ecoron/SpawnPort
commands:
 spawnport:
  description: Teleport player to worldspawn
  usage: "/spawn"
  aliases: [spawn, spawnport]
  permission: spawnport.command
permissions:
 spawnport.command:
  description: "Allows the user to teleport to worldspawn"
  default: true
 spawnport.bypass:
  description: "Allows to have admin features"
  default: op